resolver: lts-8.16

packages:
- '.'
- location:
    git: https://github.com/rybern/construction-files.git
    commit: 5999d5b5ba8e2f56e85193c5bd7570fa0c9f63ec

extra-deps: [ sparse-lin-alg-0.4.3
            , eigen-2.1.6]

flags: {}

extra-package-dbs: []

nix:
  enable: true
  packages: [liblapack, blas, git, gcc, ncurses]
