resolver: lts-9.12

packages:
- '.'
- ../shmm

extra-deps: 
- sparse-lin-alg-0.4.3
- vector-0.12.0.0
- shmm-1.0.0
- eigen-2.1.7

flags: {}

extra-package-dbs: []

nix:
  packages: [eigen, pkgconfig, zlib, gmp, ncurses, gcc]
