resolver: lts-8.16

packages:
- '.'
- location:
    git: https://github.com/rybern/construction-files.git
    commit: HEAD
  extra-dep: true

extra-deps: [ sparse-lin-alg-0.4.3
            , vector-0.12.0.0 ]

flags: {}

extra-package-dbs: []

nix:
  enable: true
  packages: [git, gcc, ncurses]
