resolver: lts-9.12

packages:
- '.'

extra-deps: 
- sparse-lin-alg-0.4.3
- vector-0.12.0.0
- eigen-3.3.4.0
- containers-0.5.8.1

flags: {}

extra-package-dbs: []

nix:
  packages: [eigen3_3, pkgconfig, zlib, gmp, ncurses, gcc, binutils]
